language: php

php:
  - '7.0'

before_script:
  - mysql -u root -e 'create database symfony;'
  - composer self-update
  - composer install

script:
  - phpunit --coverage-clover coverage.clover -c phpunit.xml.dist

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover