admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation

web:
    resource: "@WebBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"